// <auto-generated />
using System;
using EntityFrameworkMigrations.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkMigrations.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("EntityFrameworkMigrations.DataAccess.Model.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<bool>("IsMale");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<int>("ParentId");

                    b.Property<int>("SlaveId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SlaveId");

                    b.ToTable("Meow");
                });

            modelBuilder.Entity("EntityFrameworkMigrations.DataAccess.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(500);

                    b.Property<decimal>("Wage");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("EntityFrameworkMigrations.DataAccess.Model.Cat", b =>
                {
                    b.HasOne("EntityFrameworkMigrations.DataAccess.Model.Cat", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntityFrameworkMigrations.DataAccess.Model.Person", "Slave")
                        .WithMany()
                        .HasForeignKey("SlaveId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
